name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Lint Ruby code
        run: bundle exec rubocop
  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.1', '3.2', '3.3', 'head']
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        uses: paambaati/codeclimate-action@v9.0.0
        with:
          coverageCommand: bundle exec rake spec
        env:
          CC_TEST_REPORTER_ID: 0397ce028d3d53b6c9be2f649625c7529236acb2d2b6b39c6aedcafc976884ff

  macos:
    name: macOS
    runs-on: macos-latest
    strategy:
      matrix:
        ruby: ['3.1', '3.2', '3.3', 'head']
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake spec

  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: ['3.1', '3.2', '3.3', 'head']
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake spec
