name: Push gem to RubyGems.org
on:
  push:
    branches: [ "main" ]
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      # Set up
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby
      # Release
      - uses: rubygems/release-gem@v1
